name: Deploy to server via SSH

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run commands on remote via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true

          script: |
            set -e

            APP_DIR=/home/se-lab/Github/CCTVbackend/cctv-prod/Chiang-rai-cctv
            
            echo "== Go to project =="
            cd $APP_DIR
            
            echo "== Reset repo =="
            git checkout main
            git fetch origin
            git reset --hard origin/main
            git clean -fd
            
            echo "== Remove running containers =="
            docker compose down --remove-orphans || true
            
            echo "== Deploy containers =="
            docker compose up -d --build --remove-orphans
            
            echo "== Cleanup old images =="
            docker image prune -f
            
            echo "== Done =="
